### ISSUE TITLE
Please share steps of how to run the project 

### ISSUE THREAD

**Issue by devmsaleh** [JuanMorenoDeveloper/java-ee-7-certification-practice#1]
Please share steps of how to run the project

**Comment by JuanMorenoDeveloper** [comment]
Hi @devmsaleh , thanks for your interest in this one. My intention was to provide unit tests for every module, so you don't need to run the whole application, just only the unit tests (using your IDE or `mvn test`). For some modules, it generates an artifact so you can run it in an application server if you want.
